In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
dataset = pd.read_csv('diabetes.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [11]:
df=pd.read_csv("C:/Users/sanka/OneDrive/Desktop/dataset/diabetes/diabetes.csv",squeeze=True)

In [12]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)
print(X_test_norm)

[[0.05882353 1.00505051 0.62295082 ... 0.63934426 0.56191289 0.01666667]
 [0.11764706 0.54040404 0.60655738 ... 0.50074516 0.13919727 0.03333333]
 [0.23529412 0.38383838 0.50819672 ... 0.50670641 0.13364646 0.06666667]
 ...
 [0.23529412 0.71717172 0.70491803 ... 0.6557377  0.24210077 0.01666667]
 [0.17647059 0.58585859 0.60655738 ... 0.39195231 0.01238258 0.05      ]
 [0.05882353 0.54040404 0.59016393 ... 0.45901639 0.31725021 0.05      ]]


In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0,max_iter=10000,)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=0)

In [21]:
from mlxtend.evaluate import bias_variance_decomp
from sklearn import metrics
mse, bias, var = bias_variance_decomp(classifier, X_train, y_train, X_test, y_test, loss='0-1_loss', num_rounds=100, random_seed=0)
print('MSE from bias_variance lib [avg expected loss]: %.3f' % mse)
print('Avg Bias: %.3f' % bias)
print('Avg Variance: %.3f' % var)
print('Mean Square error by Sckit-learn lib: %.3f' % metrics.mean_squared_error(y_test,y_pred))

MSE from bias_variance lib [avg expected loss]: 0.194
Avg Bias: 0.175
Avg Variance: 0.040
Mean Square error by Sckit-learn lib: 0.188


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[97 10]
 [19 28]]


0.8116883116883117

In [23]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 75.39 %
Standard Deviation: 5.34 %
